### PR TITLE
#981 Localize consumption preferences

### PR DESCRIPTION
**Pull request by neil-boyette-ibm**
Added translations for both Spanish and Japanese for the new Consumption Preferences sections.

Outstanding issue is that the i18n is done rather ad-hoc and should be better/cleaner handled but as we are just updating the existing support, that work was not included here.

### CODE REVIEW

**Comment by neil-boyette-ibm** [comment]
Thanks @kognate When will this change get deployed (so I can close our issue)?

**Comment by kognate** [comment]
It's deployed now.

**Comment by neil-boyette-ibm** [comment]
awesome, thx !

**Comment by neil-boyette-ibm** [comment]
Just checked and the live (pprd) demo is complaining about the credentials. Looks like someone may have changed those (other change set ?) ?

**Comment by germanattanasio** [comment]
We are on it @neil-boyette-ibm

**Comment by neil-boyette-ibm** [comment]
thx both - you both rock :-)

**Pull request merged**
