### PR TITLE
Add link to sunburst visualization

### PR DESCRIPTION
**Pull request by vibhasinghal**

### CODE REVIEW

**Comment by germanattanasio** [comment]
@vibhasinghal I don't know why but your changes are breaking the indentation in two files. Please fix that and we can merge the PR and update the demo

**Comment by germanattanasio** [comment]
@jzhang300 can you help @vibhasinghal with this? seems like she broke the 2 spaces indentation.

**Comment by jzhang300** [comment]
@vibhasinghal I've forked your fork with some updates.  Please accept my pull request to your forked repo.

Some things I want to point out:

```html
<!-- bad -->
<p class="base--p output--more-science">
    What else do these results say?
    <a class="base--a" href="http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/personality-insights/" target="_blank">See the science behind the service</a>.
</p>
<div class="output--json">
    <h3 class="base--h3">JSON</h3>
    <pre class="base--pre language-javascript output--json-pre"><code class="base--code language-javascript output--json-code code--json"></code></pre>
</div>
<div>
    <p class="base--p output--more-science"><a class="base--a" onclick="postSunburstRequest()">View personality traits in sunburst visualization</a>.
    </p>
</div>
```

```html
<!-- good -->
<p class="base--p output--more-science">What else do these results say?
    <br>
    <a class="base--a" onclick="postSunburstRequest()" href="javascript:void(0);">View personality traits in sunburst visualization</a>.
    <br>
    <a class="base--a" href="http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/personality-insights/" target="_blank">See the science behind the service</a>.
</p>
```

* You don't want to create two containing elements with the same class name.
* Don't split elements to different containing `<div>`'s if they don't need to be.
* You can maintain the style of `<a>` tags that don't have links by giving it `href='javascript:void(0);'`

**Comment by jzhang300** [comment]
Also @vibhasinghal, we can't accept any commits that have exposed credentials in the commit history.  You can either resubmit the code changes or remove the actual credentials permanently so they don't work anymore.

**Comment by vibhasinghal** [comment]
I have fixed the indentation. 
Also, the actual credentials have been deleted, so they do not work any more.

**Comment by germanattanasio** [comment]
you are the best @vibhasinghal !

**Comment by germanattanasio** [comment]
I've updated the demo: https://personality-insights-livedemo.mybluemix.net/

**Comment by vibhasinghal** [comment]
Thanks, German and James !
Next time, I will follow good coding practices ;)

**Comment by jzhang300** [comment]
Thanks @vibhasinghal :)

**Pull request merged**
