### PR TITLE
Adding Twitter crawling capabilities for logged Twitter User.

### PR DESCRIPTION
**Pull request by arypbatista**
Deployed @ http://pi-demo-batarypa.stage1.mybluemix.net/

We added a new tab called 'Your Twitter Personality' that allows you to analyze your twitter account (authorization needed).

Also done some refactoring to views and stylized sunburst chart screen.

### CODE REVIEW

**Comment by jzhang300** [comment]
@arypbatista I liked how you separated the credentials in another json file, that's a good idea :+1:

Can you clean up the code, like spaces to tabs, remove comments, single quotes, etc.  Basically emulate coding style of some of our other demos like https://github.com/watson-developer-cloud/natural-language-classifier-nodejs.

**Comment by jzhang300** [comment]
I notice we have some ES5 scripts and some ES6 scripts, I think we should change the ES6 scripts to ES5 since majority of this app and our other apps are ES5.

**Comment by arypbatista** [comment]
Hi @jzhang300, code was cleaned up and migrated to ES5. We are now using the official PI demo's twitter app. Deployed at: http://pi-demo-batarypa.stage1.mybluemix.net/

I think we are ready to deploy. @vibhasinghal

**Comment by arypbatista** [comment]
Will merge into `twitter-personality` branch.

**Pull request closed without merging**
